#### Bag of words / Count Vectorization

In [3]:
sents = 'the red dog cat eats dog dog eats food red cat eats'

In [5]:
from nltk.tokenize import word_tokenize

In [6]:
set(word_tokenize(sents))

{'cat', 'dog', 'eats', 'food', 'red', 'the'}

In [7]:
import pandas as pd

In [8]:
sentence_1 = 'It was a good practice for us.'
sentence_2 = 'It was also good to know about it.'
sentence_3 = 'For all of us they have done a good practice.'

In [9]:
# Find all the distinct words in the senetences

In [17]:
words = word_tokenize(
    sentence_1.lower()) + word_tokenize(
    sentence_2.lower()) + word_tokenize(sentence_3.lower())

In [18]:
set(words)

{'.',
 'a',
 'about',
 'all',
 'also',
 'done',
 'for',
 'good',
 'have',
 'it',
 'know',
 'of',
 'practice',
 'they',
 'to',
 'us',
 'was'}

In [20]:
df = pd.DataFrame(columns=list(set(words)), index=[1,2,3])

In [21]:
df

,of,to,about,all,.,a,for,also,know,they,practice,done,have,good,us,it,was
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
tokens1 = word_tokenize(sentence_1.lower())
tokens2 = word_tokenize(sentence_2.lower())
tokens3 = word_tokenize(sentence_3.lower())

In [23]:
tokens1

['it', 'was', 'a', 'good', 'practice', 'for', 'us', '.']

In [24]:
tokens2

['it', 'was', 'also', 'good', 'to', 'know', 'about', 'it', '.']

In [25]:
tokens3

['for',
 'all',
 'of',
 'us',
 'they',
 'have',
 'done',
 'a',
 'good',
 'practice',
 '.']

In [28]:
counts1 = [tokens1.count(token) for token in df.columns]

In [29]:
counts1

[0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1]

In [31]:
counts2 = [tokens2.count(token) for token in df.columns]
counts2

[0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 2, 1]

In [32]:
counts3 = [tokens3.count(token) for token in df.columns]
counts3

[1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0]

In [36]:
counts1

[0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1]

In [34]:
tokens1

['it', 'was', 'a', 'good', 'practice', 'for', 'us', '.']

In [35]:
df.columns

Index(['of', 'to', 'about', 'all', '.', 'a', 'for', 'also', 'know', 'they',
       'practice', 'done', 'have', 'good', 'us', 'it', 'was'],
      dtype='object')

In [37]:
df

,of,to,about,all,.,a,for,also,know,they,practice,done,have,good,us,it,was
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
df.iloc[0,:] = counts1
df.iloc[1,:] = counts2
df.iloc[2,:] = counts3

In [41]:
df

  of to about all  .  a for also know they practice done have good us it was
1  0  0     0   0  1  1   1    0    0    0        1    0    0    1  1  1   1
2  0  1     1   0  1  0   0    1    1    0        0    0    0    1  0  2   1
3  1  0     0   1  1  1   1    0    0    1        1    1    1    1  1  0   0

In [43]:
# import the class
from sklearn.feature_extraction.text import CountVectorizer

In [44]:
# create the object 
cvt = CountVectorizer()

In [45]:
# apply the method 
x = cvt.fit_transform([sentence_1,sentence_2,sentence_3])

In [47]:
x.toarray()

array([[0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1],
       [1, 0, 1, 0, 0, 1, 0, 2, 1, 0, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0]])

In [48]:
df = pd.DataFrame(data=x.toarray(), columns=cvt.get_feature_names_out())

In [49]:
df

,about,all,also,done,for,good,have,it,know,of,practice,they,to,us,was
0,0,0,0,0,1,1,0,1,0,0,1,0,0,1,1
1,1,0,1,0,0,1,0,2,1,0,0,0,1,0,1
2,0,1,0,1,1,1,1,0,0,1,1,1,0,1,0

#### n-grams

In [51]:
cvt = CountVectorizer(ngram_range=(1,2))

In [52]:
x = cvt.fit_transform([sentence_1, sentence_2, sentence_3])

In [54]:
cvt.get_feature_names_out()

array(['about', 'about it', 'all', 'all of', 'also', 'also good', 'done',
       'done good', 'for', 'for all', 'for us', 'good', 'good practice',
       'good to', 'have', 'have done', 'it', 'it was', 'know',
       'know about', 'of', 'of us', 'practice', 'practice for', 'they',
       'they have', 'to', 'to know', 'us', 'us they', 'was', 'was also',
       'was good'], dtype=object)

In [55]:
df = pd.DataFrame(data=x.toarray(), columns=cvt.get_feature_names_out())

In [56]:
df

,about,about it,all,all of,also,also good,done,done good,for,for all,...,practice for,they,they have,to,to know,us,us they,was,was also,was good
0,0,0,0,0,0,0,0,0,1,0,...,1,0,0,0,0,1,0,1,0,1
1,1,1,0,0,1,1,0,0,0,0,...,0,0,0,1,1,0,0,1,1,0
2,0,0,1,1,0,0,1,1,1,1,...,0,1,1,0,0,1,1,0,0,0

#### TF*IDF Vectorization

In [58]:
# import the class
from sklearn.feature_extraction.text import TfidfVectorizer

In [59]:
# create the object
tfidf = TfidfVectorizer()

In [60]:
# apply the method 
x = tfidf.fit_transform([sentence_1, sentence_2,sentence_3])

In [62]:
x.toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.42246056,
        0.32807831, 0.        , 0.42246056, 0.        , 0.        ,
        0.42246056, 0.        , 0.        , 0.42246056, 0.42246056],
       [0.37162591, 0.        , 0.37162591, 0.        , 0.        ,
        0.21948825, 0.        , 0.56526217, 0.37162591, 0.        ,
        0.        , 0.        , 0.37162591, 0.        , 0.28263108],
       [0.        , 0.37571621, 0.        , 0.37571621, 0.28574186,
        0.22190405, 0.37571621, 0.        , 0.        , 0.37571621,
        0.28574186, 0.37571621, 0.        , 0.28574186, 0.        ]])

In [63]:
df = pd.DataFrame(data=x.toarray(), columns=tfidf.get_feature_names_out())

In [64]:
df

,about,all,also,done,for,good,have,it,know,of,practice,they,to,us,was
0,0.000000,0.000000,0.000000,0.000000,0.422461,0.328078,0.000000,0.422461,0.000000,0.000000,0.422461,0.000000,0.000000,0.422461,0.422461
1,0.371626,0.000000,0.371626,0.000000,0.000000,0.219488,0.000000,0.565262,0.371626,0.000000,0.000000,0.000000,0.371626,0.000000,0.282631
2,0.000000,0.375716,0.000000,0.375716,0.285742,0.221904,0.375716,0.000000,0.000000,0.375716,0.285742,0.375716,0.000000,0.285742,0.000000

#### TF*IDF on the file

In [74]:
f = open('sample_news.txt', encoding='utf-8')

In [75]:
lines = f.readlines()

In [76]:
len(lines)

3

In [78]:
x = tfidf.fit_transform(lines)

In [79]:
df = pd.DataFrame(data=x.toarray(), columns=tfidf.get_feature_names_out())

In [80]:
df

,000,2011,2014,2016,2017unfortunately,23,286,41,aaron,about,...,with,withdraw,withdrawn,works,worse,would,wrecked,year,york,you
0,0.032586,0.032586,0.032586,0.000000,0.000000,0.000000,0.032586,0.032586,0.032586,0.019246,...,0.096228,0.000000,0.000000,0.000000,0.024782,0.024782,0.000000,0.032586,0.065172,0.024782
1,0.000000,0.000000,0.000000,0.073707,0.000000,0.000000,0.000000,0.000000,0.000000,0.043533,...,0.087065,0.073707,0.000000,0.000000,0.000000,0.056056,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.042993,0.042993,0.000000,0.000000,0.000000,0.050785,...,0.050785,0.000000,0.042993,0.042993,0.032698,0.000000,0.042993,0.000000,0.000000,0.163488